import '@/styles/globals.css'
import type {AppProps} from 'next/app'
import Head from "next/head";
import Header from "@/components/ui/header/header";

export default function App({Component, pageProps}: AppProps) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/public/favicon.ico"/>
            </Head>
            <Header />
            <div className={"content"}>
                <Component {...pageProps} />
            </div>
        </div>
    )
}
